services:
  - type: web
    name: echoes-server
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GIPHY_API_KEY
        sync: false
